name: 林客商品自动化抽佣查询

on:
  workflow_dispatch:
  schedule:
    # 每天北京时间 10:00（即 UTC 时间 2:00）
    - cron: '0 2 * * *'

jobs:
  run-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: 1. 检出代码仓库
        uses: actions/checkout@v4

      - name: 2. 设置 Python 3.10 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. 安装依赖项
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. 安装 Playwright 浏览器
        run: playwright install chromium
      
      - name: 5. 安装中文字体
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: 6. 创建 config.json（来自 Secret）
        env:
          CONFIG_JSON_CONTENT: ${{ secrets.CONFIG_JSON }}
        run: |
          echo "$CONFIG_JSON_CONTENT" > config.json
          echo "config.json 创建成功。"

      - name: 7. 运行 Python 脚本
        run: python chouyong_cli.py

      - name: 8. 上传日志与调试文件
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: execution-artifacts
          path: |
            logs/
            debug_artifacts/
