# 工作流的名称，会显示在GitHub Actions页面
name: linkezidonghua

on:
  # 允许您在GitHub Actions页面手动触发此工作流
  workflow_dispatch:
  
  # 设置定时任务
  schedule:
    # cron表达式，表示在每天的UTC时间03:00（即北京时间11:00）运行
    - cron: '0 3 * * *'

jobs:
  # 任务的ID
  run-tasks:
    # 任务的名称，会显示在运行日志中
    name: 执行佣金同步与查询
    
    # 指定运行环境为最新的Ubuntu系统
    runs-on: ubuntu-latest

    steps:
      - name: 第1步: 拉取代码仓库
        uses: actions/checkout@v4

      - name: 第2步: 设置Python 3.10环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 第3步: 安装Python依赖包
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 第4步: 安装Playwright所需的浏览器
        run: playwright install chromium
      
      - name: 第5步: 安装中文字体
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk
        
      - name: 第6步: 从Secrets创建配置文件
        env:
          CONFIG_JSON_CONTENT: ${{ secrets.CONFIG_JSON }}
        run: |
          echo "$CONFIG_JSON_CONTENT" > config.json
          echo "配置文件创建成功。"

      - name: 第7步: 运行主程序脚本
        run: python chouyong_cli.py

      - name: 第8步: 上传日志与调试文件
        # if: always() 确保无论成功或失败，这一步都会执行
        if: always()
        uses: actions/upload-artifact@v4
        with:
          # 上传的产物包名称
          name: 任务执行产物
          # 要上传的文件夹路径
          path: |
            logs/
            debug_artifacts/
