name: Run Commission Tasks

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 1 * * *'

jobs:
  run-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Install Playwright browsers
        run: playwright install chromium
      
      - name: 5. Install Chinese Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk
        
      - name: 6. Create config.json from Secret
        env:
          CONFIG_JSON_CONTENT: ${{ secrets.CONFIG_JSON }}
        run: |
          echo "$CONFIG_JSON_CONTENT" > config.json
          echo "config.json created successfully."

      - name: 7. Run the Python script
        # 已移除不再需要的 env 环境变量
        run: python chouyong_cli.py

      - name: 8. Upload logs and debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: execution-artifacts
          path: |
            logs/
            debug_artifacts/
