name: Run Commission Tasks

on:
  # 允许你手动在 GitHub Actions 页面点击 "Run workflow" 来触发
  workflow_dispatch:

  # 也可以设置定时任务，例如每天北京时间上午9点运行
  # schedule:
  #   - cron: '0 1 * * *' # Cron 语法，这是 UTC 时间 1:00 AM

jobs:
  run-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        # 这步会把你仓库里所有的文件（包括代码、json、xlsx）都拉取到虚拟机
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Install Playwright browsers
        run: playwright install chromium

      - name: 5. Create config.json from Secret
        # 我们仍然使用 Secret 来管理 config.json，因为里面的密钥最敏感
        env:
          CONFIG_JSON_CONTENT: ${{ secrets.CONFIG_JSON }}
        run: |
          echo "$CONFIG_JSON_CONTENT" > config.json
          echo "config.json created successfully."

      - name: 6. Run the Python script
        # 脚本会自动在当前目录找到 林客.json 和 门店ID.xlsx
        run: python chouyong_cli.py

      - name: 7. Upload logs as artifact
        if: always() # 无论成功或失败，都上传日志
        uses: actions/upload-artifact@v4
        with:
          name: execution-logs
          path: logs/
