name: ETH价格追踪 (Playwright版)

on:
  schedule:
    - cron: '0 * * * *'  # 每小时的第0分钟执行
  workflow_dispatch:      # 允许手动触发

jobs:
  fetch-and-send:
    runs-on: ubuntu-latest
    
    container:
      image: mcr.microsoft.com/playwright/python:v1.53.0-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install playwright requests
          
      - name: Run script
        env:
          APPID: ${{ secrets.APPID }}
          APPSECRET: ${{ secrets.APPSECRET }}
          OPENID: ${{ secrets.OPENID }}
          ETH_TEMPLATE_ID: ${{ secrets.ETH_TEMPLATE_ID }}
        run: python eth_playwright.py
