name: Ethereum Price Reporter

on:
  schedule:
    # 每小时运行一次
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  report-price:
    runs-on: ubuntu-latest

    # --- 核心修改：为整个 Job 授予写入内容的权限 ---
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      # --- 核心修改：移除了 persist-credentials: false ---
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests openai

    # 调试步骤，保持不变
    - name: Show history file content before script runs
      run: |
        echo "--- Content of eth_price_history.json BEFORE script ---"
        if [ -f eth_price_history.json ]; then
          cat eth_price_history.json
        else
          echo "eth_price_history.json does not exist yet."
        fi
        echo "----------------------------------------------------"

    - name: Run the script to fetch price and update history
      env:
        APPID: ${{ secrets.APPID }}
        APPSECRET: ${{ secrets.APPSECRET }}
        OPENID: ${{ secrets.OPENID }}
        ETH_TEMPLATE_ID: ${{ secrets.ETH_TEMPLATE_ID }}
        LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
      run: python eth_api.py
      
    # 调试步骤，保持不变
    - name: Show history file content after script runs
      run: |
        echo "--- Content of eth_price_history.json AFTER script ---"
        cat eth_price_history.json
        echo "---------------------------------------------------"

    - name: Commit and push updated price history
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: Update ETH price history"
        file_pattern: eth_price_history.json
        commit_user_name: "GitHub Actions Bot"
        commit_user_email: "github-actions[bot]@users.noreply.github.com"
        # --- 核心修改：移除了无效的 skip_empty_commit 参数 ---
