name: Ethereum Price Reporter

on:
  schedule:
    # 每小时运行一次
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  report-price:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests openai # <--- 在这里添加 openai

    - name: Cache ETH price history
      id: cache-history
      uses: actions/cache@v3
      with:
        path: eth_price_history.json
        key: ${{ runner.os }}-eth-history-cache-v1
        # restore-keys 也可以指向同一个 key，确保能找到
        restore-keys: |
          ${{ runner.os }}-eth-history-cache-v1
          
    - name: Run the script
      env:
        APPID: ${{ secrets.APPID }}
        APPSECRET: ${{ secrets.APPSECRET }}
        OPENID: ${{ secrets.OPENID }}
        ETH_TEMPLATE_ID: ${{ secrets.ETH_TEMPLATE_ID }}
        LLM_API_KEY: ${{ secrets.LLM_API_KEY }} # <--- 在这里添加新的 secret
      run: python eth_api.py
