name: ETH价格追踪

on:
  schedule:
    - cron: '*/30 * * * *'  # 每 30 分钟运行
  workflow_dispatch: # 添加 workflow_dispatch 事件，允许手动触发

jobs:
  fetch-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 requests

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y chromium-chromedriver

      - name: Kill Chrome processes
        run: |
          pkill chrome || true
          pkill chromedriver || true

      - name: Check /tmp directory space
        run: |
          df -h /tmp

      - name: List directory contents
        run: |
          ls -l

      - name: Find working directory
        id: get-working-directory
        run: |
          echo "WORKING_DIRECTORY=$(pwd)" >> $GITHUB_OUTPUT

      - name: Run script
        run: |
          set -x
          python ${{ steps.get-working-directory.outputs.WORKING_DIRECTORY }}/eth.py --driver_path chromedriver
