name: ETH价格追踪

on:
  schedule:
    - cron: '*/5 * * * *'  # 每隔 5 分钟运行
  workflow_dispatch: # 添加 workflow_dispatch 事件

jobs:
  fetch-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 requests html5lib

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y chromium-chromedriver

      - name: Make chromedriver executable
        run: |
          chmod +x chromedriver

      - name: Find Chromedriver Path
        id: chromedriver-path
        run: |
          CHROMEDRIVER_PATH=$(which chromedriver)
          echo "CHROMEDRIVER_PATH=$CHROMEDRIVER_PATH"
          echo "::set-output name=CHROMEDRIVER_PATH::$CHROMEDRIVER_PATH"

      - name: Run script
        env:
          APPID: ${{ secrets.APPID }}  # 从 secrets 获取
          APPSECRET: ${{ secrets.APPSECRET }}  # 从 secrets 获取
          OPENID: ${{ secrets.OPENID }}  # 从 secrets 获取
          ETH_TEMPLATE_ID: ${{ secrets.ETH_TEMPLATE_ID }}  # 从 secrets 获取
        run: |
          set -x
          python eth.py --driver_path ${{ steps.chromedriver-path.outputs.CHROMEDRIVER_PATH }}
