name: ETH价格追踪 (Playwright版 - 使用缓存优化)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  fetch-and-send:
    runs-on: ubuntu-latest
    
    container:
      image: mcr.microsoft.com/playwright/python:v1.53.0-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- 新增的缓存步骤 ---
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          # 指定要缓存的目录路径 (pip 的默认缓存目录)
          path: ~/.cache/pip
          # 定义缓存的唯一密钥。我们用工作流文件本身的哈希值作为关键部分。
          # 这样，只有当你修改这个文件时（比如增删了要安装的包），缓存才会失效。
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/your-workflow-filename.yml') }}
          # 定义备用密钥，用于部分匹配
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install playwright requests
          
      - name: Run script
        env:
          APPID: ${{ secrets.APPID }}
          APPSECRET: ${{ secrets.APPSECRET }}
          OPENID: ${{ secrets.OPENID }}
          ETH_TEMPLATE_ID: ${{ secrets.ETH_TEMPLATE_ID }}
        run: python eth_playwright.py
