name: Fetch and Send Hot News

on:
  schedule:
    - cron: '47 8 * * *'  # 每天 UTC 时间 8:47 运行
  workflow_dispatch: # 添加 workflow_dispatch 事件

jobs:
  fetch-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 requests

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Get Chromium version and download chromedriver
        id: get_chromium_driver
        run: |
          chromium_version=$(chromium-browser --version | grep -oP '\d+\.\d+\.\d+')
          echo "Chromium version: $chromium_version"
          latest_version=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          echo "Latest Chromedriver version: $latest_version"

          specific_chromedriver_version=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json"  | jq -r ".versions[] | select(.version == \"$chromium_version\" ) | .downloads.chromedriver[0].url" )

          if [[ -z "$specific_chromedriver_version" ]]; then
              echo "Use latest chromedriver"
              wget https://chromedriver.storage.googleapis.com/$latest_version/chromedriver_linux64.zip
          else
               echo "Use specific chromedriver"
               wget "$specific_chromedriver_version"
               unzip chromedriver*
          fi

          chmod +x chromedriver
          echo "::set-output name=driver_path::$(pwd)/chromedriver"

      - name: Run script
        env:
          WECOM_WEBHOOK_KEY: ${{ secrets.WECOM_WEBHOOK_KEY }}
        run: |
          set -x
          /opt/hostedtoolcache/Python/3.12.8/x64/bin/python news.py --driver_path ${{ steps.get_chromium_driver.outputs.driver_path }}
