name: Fetch and Send Hot News

on:
  schedule:
    - cron: '47 8 * * *'  # 每天 UTC 时间 8:47 运行
  workflow_dispatch: # 添加 workflow_dispatch 事件

jobs:
  fetch-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 requests

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - name: Download specific Chromium and Chromedriver
        id: download_chromium_driver
        run: |
           chromium_version="113.0.5672.24"
           echo "Using specific Chromium version: $chromium_version"

           specific_chromedriver_version=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json"  | jq -r ".versions[] | select(.version == \"$chromium_version\" ) | .downloads.chromedriver[0].url" )
           echo "Specific Chromedriver version: $specific_chromedriver_version"
           
           wget $specific_chromedriver_version
           unzip chromedriver*
           chmod +x chromedriver
           
           
           wget "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F${chromium_version}%2Fchrome-linux.zip?alt=media" -O chrome-linux.zip
           unzip chrome-linux.zip
           chmod +x chrome-linux/chrome

           echo "::set-output name=chromium_path::$(pwd)/chrome-linux/chrome"
           echo "::set-output name=driver_path::$(pwd)/chromedriver"


      - name: Run script
        env:
          WECOM_WEBHOOK_KEY: ${{ secrets.WECOM_WEBHOOK_KEY }}
        run: |
          set -x
          /opt/hostedtoolcache/Python/3.12.8/x64/bin/python news.py --driver_path ${{ steps.download_chromium_driver.outputs.driver_path }} --chromium_path ${{ steps.download_chromium_driver.outputs.chromium_path }}
