name: Fetch and Send Hot News

on:
  schedule:
    - cron: '47 8 * * *'  # 每天 UTC 时间 8:47 运行
  workflow_dispatch: # 添加 workflow_dispatch 事件

jobs:
  fetch-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 requests

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Get Latest Chrome Driver Version
        id: get_chromedriver_version
        run: |
          latest_version=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          echo "::set-output name=version::$latest_version"

      - name: Download Chrome Driver
        run: |
          wget https://chromedriver.storage.googleapis.com/${{ steps.get_chromedriver_version.outputs.version }}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          chmod +x chromedriver

      - name: Run script
        env:
          WECOM_WEBHOOK_KEY: ${{ secrets.WECOM_WEBHOOK_KEY }}
        run: |
          python news.py
