name: Fetch and Send Hot News

on:
  schedule:
    - cron: '47 8 * * *'  # 每天 UTC 时间 8:47 运行
  workflow_dispatch: # 添加 workflow_dispatch 事件

jobs:
  fetch-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 requests

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Get Chromium version and download chromedriver
        id: get_chromium_driver
        run: |
          chromium_version=$(chromium-browser --version | grep -oP '\d+\.\d+\.\d+')
          echo "Chromium version: $chromium_version"
          chromedriver_version=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${chromium_version}")
          echo "Chromedriver version: $chromedriver_version"
          wget https://chromedriver.storage.googleapis.com/$chromedriver_version/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          echo "::set-output name=driver_path::$(pwd)/chromedriver"


      - name: Run script
        env:
          WECOM_WEBHOOK_KEY: ${{ secrets.WECOM_WEBHOOK_KEY }}
        run: |
          python news.py --driver_path ${{ steps.get_chromium_driver.outputs.driver_path }}
