name: Fetch and Send Hot News

on:
  schedule:
    - cron: '43 8 * * *'

jobs:
  fetch-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 requests

      - name: Download Edge Driver
        run: |
          wget https://msedgedriver.azureedge.net/120.0.2210.133/edgedriver_linux64.zip
          unzip edgedriver_linux64.zip
          chmod +x msedgedriver

      - name: Run script
        env:
          WECOM_WEBHOOK_KEY: ${{ secrets.WECOM_WEBHOOK_KEY }}
        run: |
          python your_script.py
