# 文件路径: /.github/workflows/xiaohongshu.yml

name: Run Xiaohongshu Uploader via API

on:
  repository_dispatch:
    types: [run-uploader]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 确保你的 requirements.txt 文件包含 playwright 和 requests
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: playwright install --with-deps chromium
      
      - name: Create cookie file from secret
        env:
          XHS_COOKIES_JSON: ${{ secrets.XHS_COOKIES_JSON }}
        run: echo "$XHS_COOKIES_JSON" > 小红书.json
      
      - name: Run the uploader script
        env:
          # 从仓库变量中读取图片链接JSON
          IMAGE_URLS_JSON: ${{ vars.IMAGE_URLS_JSON }}
          # 从触发事件的 client_payload 中读取标题和描述
          NOTE_TITLE_FROM_API: ${{ github.event.client_payload.title }}
          NOTE_DESC_FROM_API: ${{ github.event.client_payload.description }}
        run: python run_xiaohongshu.py

      - name: Upload final screenshot
        uses: actions/upload-artifact@v4
        with:
          name: final-screenshot
          path: |
            final_screenshot.png
            error_screenshot.png
          if-no-files-found: 'ignore'
