# Workflow 的名称
name: Run Xiaohongshu Uploader

# 触发器：当手动触发时运行此工作流
on:
  workflow_dispatch:

# 定义工作任务
jobs:
  build-and-run:
    # 使用最新的 Ubuntu 系统作为运行环境
    runs-on: ubuntu-latest

    steps:
      # 第1步: 检出你的代码库
      - name: Check out repository code
        uses: actions/checkout@v4

      # 第2步: 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 第3步: 安装 Python 依赖库
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 第4步: 安装 Playwright 的浏览器依赖
      # --with-deps 会自动安装所有需要的系统库
      - name: Install Playwright Browsers
        run: playwright install --with-deps chromium

      # 第5步: 从 GitHub Secrets 创建 Cookie 文件 (关键安全步骤)
      # 脚本将从这个文件中读取 cookie，避免将敏感信息直接写入代码库
      - name: Create cookie file from secret
        env:
          # 将名为 XHS_COOKIES_JSON 的 Secret 注入到环境变量中
          XHS_COOKIES_JSON: ${{ secrets.XHS_COOKIES_JSON }}
        run: |
          echo "正在创建 小红书.json 文件..."
          echo "$XHS_COOKIES_JSON" > 小红书.json
          echo "文件创建成功。"

      # 第6步: 运行你的 Python 脚本
      - name: Run the uploader script
        run: python run_xiaohongshu.py

      # 第7步: 上传截图作为 "Artifact" (产物)
      # 这样你就可以在 Action 运行结束后下载并查看截图
      - name: Upload final screenshot
        uses: actions/upload-artifact@v4
        with:
          name: final-screenshot
          path: |
            final_screenshot.png
            error_screenshot.png
          if-no-files-found: 'ignore' # 如果文件不存在，忽略此步骤
