name: Run Xiaohongshu Uploader via API

on:
  repository_dispatch:
    types: [run-uploader]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      # 第1步：检出你的代码库
      # 这个步骤完成后，你仓库里所有的文件，包括 run_xiaohongshu.py 和 小红书.json
      # 都会出现在 GitHub Actions 的运行环境中。
      - name: Check out repository code
        uses: actions/checkout@v4

      # 第2步：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 第3步：安装 Python 依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 第4步：安装 Playwright 的浏览器
      - name: Install Playwright Browsers
        run: playwright install --with-deps chromium

      # 第5步：直接运行你的 Python 脚本
      # 因为上一步 checkout 已经把 小红书.json 文件准备好了，
      # 所以脚本可以直接读取它，就像在本地一样。
      - name: Run the uploader script
        run: python run_xiaohongshu.py

      # 第6步：上传截图作为产物
      - name: Upload final screenshot
        uses: actions/upload-artifact@v4
        with:
          name: final-screenshot
          path: |
            final_screenshot.png
            error_screenshot.png
          if-no-files-found: 'ignore'
