name: 林客商品自动化抽佣查询

on:
  # 1. 保留手动触发
  workflow_dispatch:

  # 2. 保留定时触发 (每天北京时间 9:00)
  schedule:
    - cron: '0 1 * * *'

  # 3. 【修改】当只有 chouyong_cli.py 文件被推送到 main 分支时触发
  push:
    branches:
      - main  # 或者您的主分支名，例如 master
    paths:
      - 'chouyong_cli.py' # 只监控这一个文件的变化

jobs:
  run-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: 1. 检出代码仓库
        uses: actions/checkout@v4

      - name: 2. 设置 Python 3.10 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. 安装依赖项
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. 安装 Playwright 浏览器
        run: playwright install chromium
      
      - name: 5. 安装中文字体
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: 6. 设置环境变量
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
        run: |
          echo "环境变量设置完成。"

      - name: 7. 运行 Python 脚本
        run: python chouyong_cli.py

      - name: 8. 上传日志与调试文件
        if: always() # 确保无论成功或失败，都上传产物
        uses: actions/upload-artifact@v4
        with:
          name: execution-artifacts
          path: |
            logs/
            debug_artifacts/
