name: 【抖音来客】经营分更新
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.53.0-jammy
    steps:
      - name: 导入代码
        uses: actions/checkout@v4

      - name: 安装依赖
        run: pip install playwright pandas lark-oapi
        
      - name: 运行脚本
        env:
          FEISHU_APP_ID_FROM_SECRET: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET_FROM_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
        run: python 更新经营分数据.py
