name: 【抖音来客】客服人员监控

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 0,8 * * *' # 每天的 UTC 时间 0点 和 8点 运行

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright/python:v1.54.0-jammy

    steps:
      - name: 导入代码
        uses: actions/checkout@v4
        
      - name: 安装依赖
        run: pip install requests playwright==1.54.0

      - name: 运行监控脚本
        id: run-script
        run: python 【抖音来客】客服人员查询.py
        
      - name: 上传失败时的调试截图
        # 这个条件现在可以正确工作了，因为脚本在失败时会返回非零退出码
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshot 
          path: ./*.png
          retention-days: 7
