name: 【抖音来客】评价数据自动同步

on:
  # 1. 允许在 GitHub Actions 页面手动触发
  workflow_dispatch:

  # 2. 定时执行 (使用 cron 语法)
  schedule:
    - cron: '0 2,7 * * *'

  push:
    branches:
      - main      # 如果您的主分支是 'master'，请修改为 'master'
    paths:
      - '同步评价信息.py' # <-- 注意这里的文件名要和您的脚本名一致
      - '.github/workflows/**.yml'

jobs:
  sync-comment-data:
    runs-on: ubuntu-latest
    
    container:
      # 使用微软官方提供的 Playwright Python 镜像，已预装所有依赖
      image: mcr.microsoft.com/playwright/python:v1.53.0-jammy

    steps:
      - name: 导入代码和Cookie文件
        # 拉取仓库中的所有文件，包括 .py 和 .json 文件
        uses: actions/checkout@v4

      - name: 安装 Python 依赖
        run: |
          pip install playwright==1.53.0 pandas openpyxl lark-oapi

      - name: 运行自动化脚本
        env:
          # 从 GitHub Secrets 中读取密钥，并将其设置为环境变量
          # 这是管理密钥的最佳实践
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
        
        # 运行您的Python脚本
        run: python 同步评价信息.py # <-- 注意这里的文件名要和您的脚本名一致

      - name: 上传错误截图 (如果任务失败)
        # `if: failure()` 确保此步骤只在前面的步骤失败时运行
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          # 上传后的文件包名称
          name: error-screenshot-artifact
          # 需要上传的文件路径，与Python脚本中定义的一致
          path: error_screenshot.png
