name: 【抖音来客】经营分更新
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.53.0-jammy
    steps:
      - name: 导入代码
        uses: actions/checkout@v4


jobs:
  run-laike-monitor:
    # 使用最新的 Ubuntu 虚拟机环境来运行
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出仓库代码
      # 这会将你的 .py 和 .json 文件下载到虚拟机中
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：设置 Python 环境
      # 指定使用的 Python 版本
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 第三步：安装 Python 依赖库
      # 安装脚本运行所需要的 'requests' 和 'playwright'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright

      # 第四步：安装 Playwright 所需的浏览器
      # 我们的脚本使用的是 Chromium，所以只安装它以节省时间
      - name: Install Playwright Chromium Browser
        run: playwright install chromium

      # 第五步：运行监控脚本
      # 执行你的 Python 文件。
      # 注意：因为文件名包含中文和空格，所以必须用双引号括起来！
      - name: Run Douyin Laike Monitor Script
        run: python "【抖音来客】客服人员查询.py"
