name: 更新门店数据

on:
  workflow_dispatch:

  # 每天 0:00 UTC (北京时间上午8:00) 自动运行
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.53.0-jammy

    steps:
      - name: 导入代码
        uses: actions/checkout@v4

      - name: 安装 Python 依赖
        run: pip install playwright pandas lark-oapi openpyxl

      - name: 运行同步脚本
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
        run: python 更新门店数据.py
