# .github/workflows/sync_douyin_data.yml

name: 更新经营分数据

on:
  # 1. 允许手动触发工作流
  workflow_dispatch:

  # 2. 定时触发：每天上午10点 (注意：GitHub Actions 使用 UTC 时间)
  #    北京时间 (UTC+8) 的上午10点，对应 UTC 时间是凌晨2点。
  schedule:
    - cron: '0 2 * * *'

jobs:
  sync-data:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 虚拟机环境

    steps:
      # 第1步：检出（下载）你的仓库代码到虚拟机
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第2步：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # 指定与您本地一致的 Python 版本

      # 第3步：安装 Playwright 的浏览器驱动
      # 这一步非常重要，否则 Playwright 无法启动浏览器
      - name: Install Playwright Browsers
        run: python -m playwright install --with-deps

      # 第4步：安装 Python 依赖库
      # 从 requirements.txt 文件安装，这是最佳实践
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      # 第5步：运行你的 Python 脚本
      # 使用 env 来将 GitHub Secrets 作为环境变量传递给脚本
      - name: Run the sync script
        env:
          # 将 GitHub Secrets 赋值给环境变量
          FEISHU_APP_ID_FROM_SECRET: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET_FROM_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
        run: python 更新经营分数据.py
