name: 经营分数据更新

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.53.0-jammy # 建议指定一个具体的版本以保证稳定性

    steps:
      # 第1步：检出（下载）你的仓库代码到容器中
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 安装相关依赖
        run: pip install -r requirements.txt
          
      - name: 运行你的 Python 脚本
        env:
          FEISHU_APP_ID_FROM_SECRET: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET_FROM_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
        run: python 更新经营分数据.py
